#    ______ _                       _    _
#    | ___ \ |                     | |  | |
#    | |_/ / | __ _ _   _  ___ _ __| |  | | __ _ _ __ _ __  ___
#    |  __/| |/ _` | | | |/ _ \ '__| |/\| |/ _` | '__| '_ \/ __|
#    | |   | | (_| | |_| |  __/ |  \  /\  / (_| | |  | |_) \__ \
#    \_|   |_|\__,_|\__, |\___|_|   \/  \/ \__,_|_|  | .__/|___/
#                   __/ |                            | |
#                 |___/                             |_|
#
#                                                by Revivalo
#
# If you have some questions, join https://discord.gg/TfUC8uJ for help
#
# From 1.16 version you can also use HEX colors.
# Instead of &f format use <#ffffff>
#
config:
  language: English
  update-checker: true
  autosave-enabled: true # recommended setting to true
  autosave-announce: true
  date-format: dd/MM/yyyy
  warp-name-format: "&b&n%warpName%"
  # 30 minutes is recommended
  autosave-interval: 30 # in minutes
  teleport-delay: 3
  currency-symbol: "$"
  allow-colors-in-warp-display-names: true
  # This option works only with installed Vault plugin
  # For no price just set it to 0
  warp-price: 5000
  # To disable the fee features, set them to 0
  relocate-warp-fee: 1000
  rename-warp-fee: 500
  transfer-ownership-fee: 0
  set-status-fee: 0
  set-type-fee: 0
  set-preview-item-fee: 0
  set-description-fee: 0
  set-display-name-fee: 200
  set-admission-fee: 0
  # To disable refund set to 0
  delete-warp-refund: 2000
  max-warp-admission: 100000
  # Make sure you are using valid IDs
  default-warp-item: ENDER_PEARL
  banned-items:
    - DEBUG_STICK
    - BARRIER
    - STRUCTURE_VOID
  default-limit-size: 1
  warp-name-max-length: 24
  disabled-worlds:
    - disabledworld1
    - disabledworld2
    - disabledworld3
  enable-categories: true
  # Set none to disable this option
  categories-background-item: LIGHT_GRAY_STAINED_GLASS_PANE

  # This option note player that warp teleportation is charged
  allow-teleport-accept-menu: true
  # Checking if the warp destination is safe (fire, lava, fall from a height or of the world)
  check-for-safe-teleport: true
  warp-list-item: PAPER
  my-warps-item: REPEATER
  help-item: OAK_SIGN
  favorite-warps-item: NAME_TAG
  page-item: ARROW
  star-review-item: SUNFLOWER
  back-item: OAK_BUTTON