name: PlayerWarps
authors: [Revivalo]
description: Warps created by players for players
version: ${project.version}

main: dev.revivalo.playerwarps.PlayerWarpsPlugin
api-version: 1.13
softdepend:
  - Vault
  - Multiverse-Core
  - Multiworld
  - DiscordSRV
  - ChatControlRed
  - ChatControl
  - Essentials

commands:
  pwarp:
    description: Main command for PlayerWarps plugin
    usage: /<command>
    aliases: [pw, playerwarps]

permissions:
  playerwarps.use:
    description: Allows you to teleport to public warps
    default: true
  playerwarps.create:
    description: Allows you to create a warp
    default: true
  playerwarps.settings:
    description: Allows you to setup the warp
    default: true